### PR TITLE
hspell: Correct usage of g_return_val_if_fail and g_warning

### LINKED ISSUE #394: Epiphany crash due to hspell when entering special Hebrew characters (e.g., ׳)
## Version information
* hspell 1.4
* enchant 2.8.0
* WebKitGTK 2.45.5
* GTK 4.15.5.r119.g99d291eb69-1
* Libadwaita 1.6.beta.r7.ga645fef6-1
* Epiphany 47.beta-7-gc6104693f
* Distributor: Arch Linux

## Description
Epiphany crashes when typing certain special Hebrew characters, such as the character ׳, in a text field. This issue seems to be related to the hspell spell-checking library, which fails when processing words containing these characters.

**Steps to Reproduce:**
0. Make sure you have hspell installed
1. Open a terminal and set the locale to Hebrew:  
   `LC_ALL=he_IL.UTF-8 epiphany`
2. Navigate to a website with a text input field, such as GitLab.
3. Type a word containing the special Hebrew character ׳ (e.g., "׳לו").
4. Observe the crash.

**Actual Result:**
Epiphany crashes with a SIGTRAP signal.

**Expected Result:**
Epiphany should handle the special Hebrew characters without crashing.

**Additional Information:**
Partial `gdb` backtrace:
```
❯ gdb epiphany
GNU gdb (GDB) 15.1
Copyright (C) 2024 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from epiphany...
(gdb) run
Starting program: /usr/bin/epiphany

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for /lib64/ld-linux-x86-64.so.2
Downloading separate debug info for system-supplied DSO at 0x7ffff7fc5000
Downloading separate debug info for /usr/lib/libgio-2.0.so.0
Downloading separate debug info for /usr/lib/libgobject-2.0.so.0
Downloading separate debug info for /usr/lib/libglib-2.0.so.0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Downloading separate debug info for /usr/lib/libgmodule-2.0.so.0
[New Thread 0x7fffe11256c0 (LWP 603260)]
[New Thread 0x7fffe09246c0 (LWP 603264)]
[New Thread 0x7fffdbfff6c0 (LWP 603265)]
[New Thread 0x7fffdb7fe6c0 (LWP 603266)]
[New Thread 0x7fffdaffd6c0 (LWP 603267)]
[New Thread 0x7fffcffff6c0 (LWP 603268)]
[Thread 0x7fffdaffd6c0 (LWP 603267) exited]
[New Thread 0x7fffdaffd6c0 (LWP 603297)]
[New Thread 0x7fffcd0be6c0 (LWP 603298)]
[New Thread 0x7fffcc8bd6c0 (LWP 603299)]
[New Thread 0x7fff7fffd6c0 (LWP 603300)]
[New Thread 0x7fff7f7fc6c0 (LWP 603301)]
[New Thread 0x7fff7cffb6c0 (LWP 603302)]
[New Thread 0x7fff6fdff6c0 (LWP 603303)]
[New Thread 0x7fff6f5fe6c0 (LWP 603304)]
[Thread 0x7fff6f5fe6c0 (LWP 603304) exited]
[Detaching after vfork from child process 603305]
[New Thread 0x7fff6f5fe6c0 (LWP 603312)]
[New Thread 0x7fff6edfd6c0 (LWP 603313)]
[New Thread 0x7fff6e5fc6c0 (LWP 603314)]
[New Thread 0x7fff6ddfb6c0 (LWP 603315)]
[New Thread 0x7fff6d5fa6c0 (LWP 603317)]
[New Thread 0x7fff6cdf96c0 (LWP 603318)]
[New Thread 0x7fff3f1ff6c0 (LWP 603324)]
[New Thread 0x7fff3e9fe6c0 (LWP 603326)]
[New Thread 0x7fff3e1fd6c0 (LWP 603327)]
[New Thread 0x7fff3d9fc6c0 (LWP 603328)]
[Thread 0x7fff3e1fd6c0 (LWP 603327) exited]
[Thread 0x7fff3e9fe6c0 (LWP 603326) exited]
[Thread 0x7fff6ddfb6c0 (LWP 603315) exited]
[New Thread 0x7fff3e1fd6c0 (LWP 603331)]
[New Thread 0x7fff3e9fe6c0 (LWP 603333)]
[New Thread 0x7fff6ddfb6c0 (LWP 603334)]
[New Thread 0x7fff2ffff6c0 (LWP 603335)]
[New Thread 0x7fff2d7ff6c0 (LWP 603337)]
[Thread 0x7fff3e1fd6c0 (LWP 603331) exited]
[Thread 0x7fff6ddfb6c0 (LWP 603334) exited]
[Thread 0x7fff3e9fe6c0 (LWP 603333) exited]
[Thread 0x7fff3d9fc6c0 (LWP 603328) exited]
[New Thread 0x7fff6ddfb6c0 (LWP 603338)]
[New Thread 0x7fff3e9fe6c0 (LWP 603339)]
[New Thread 0x7fff3d9fc6c0 (LWP 603340)]
[New Thread 0x7fff3e1fd6c0 (LWP 603341)]
MESA-INTEL: warning: ../mesa-24.1.5/src/intel/vulkan/anv_formats.c:763: FINISHME: support YUV colorspace with DRM format modifiers
MESA-INTEL: warning: ../mesa-24.1.5/src/intel/vulkan/anv_formats.c:794: FINISHME: support more multi-planar formats with DRM modifiers
[New Thread 0x7fff2cffe6c0 (LWP 603342)]
[New Thread 0x7fff1bfff6c0 (LWP 603343)]
[Detaching after fork from child process 603344]
[Detaching after vfork from child process 603345]
[Detaching after vfork from child process 603350]

(epiphany:603226): epiphany-WARNING **: 12:19:35.902: Failed to load extension /home/yoseforb/.local/share/epiphany/web_extensions/video_downloadhelper-8.1.4.0.xpi: חסר שם או גרסה

(epiphany:603226): epiphany-WARNING **: 12:19:35.902: Failed to load extension /home/yoseforb/.local/share/epiphany/web_extensions/turn_off_the_lights-4.4.5.0.xpi: רק manifest_version 2 נתמך
[New Thread 0x7fff1b7fe6c0 (LWP 603353)]
[New Thread 0x7fff1affd6c0 (LWP 603354)]
[New Thread 0x7fff1a7fc6c0 (LWP 603355)]
[New Thread 0x7fff19ffb6c0 (LWP 603356)]
[Detaching after vfork from child process 603366]
[Detaching after vfork from child process 603368]
[New Thread 0x7fff197fa6c0 (LWP 603372)]
[New Thread 0x7fff18ff96c0 (LWP 603374)]
[Detaching after vfork from child process 603376]
[New Thread 0x7ffefbfff6c0 (LWP 603378)]
[Detaching after vfork from child process 603382]
[New Thread 0x7ffefb7fe6c0 (LWP 603394)]
[New Thread 0x7ffefaffd6c0 (LWP 603424)]
Failed to create GBM buffer of size 0x0: Invalid argument
[New Thread 0x7ffefa7fc6c0 (LWP 603447)]
[Thread 0x7fff19ffb6c0 (LWP 603356) exited]
[Thread 0x7fff1a7fc6c0 (LWP 603355) exited]
[Thread 0x7fff2ffff6c0 (LWP 603335) exited]
[New Thread 0x7fff2ffff6c0 (LWP 603532)]
[New Thread 0x7fff1a7fc6c0 (LWP 603533)]
[New Thread 0x7fff19ffb6c0 (LWP 603534)]
[New Thread 0x7ffef9ffb6c0 (LWP 603535)]
[New Thread 0x7ffef97fa6c0 (LWP 603536)]
[New Thread 0x7ffef8ff96c0 (LWP 603538)]
[New Thread 0x7ffee3fff6c0 (LWP 603541)]
[New Thread 0x7ffee37fe6c0 (LWP 603542)]
[Thread 0x7ffef8ff96c0 (LWP 603538) exited]
[Thread 0x7ffee3fff6c0 (LWP 603541) exited]
[Thread 0x7ffef97fa6c0 (LWP 603536) exited]
[Thread 0x7fff1affd6c0 (LWP 603354) exited]
[Thread 0x7ffef9ffb6c0 (LWP 603535) exited]
[Thread 0x7fff2ffff6c0 (LWP 603532) exited]
[Thread 0x7ffee37fe6c0 (LWP 603542) exited]
[Thread 0x7fff19ffb6c0 (LWP 603534) exited]
[Thread 0x7fff1a7fc6c0 (LWP 603533) exited]
[Thread 0x7ffefaffd6c0 (LWP 603424) exited]
[Thread 0x7fff7f7fc6c0 (LWP 603301) exited]
[Thread 0x7ffefa7fc6c0 (LWP 603447) exited]
[New Thread 0x7ffefa7fc6c0 (LWP 603691)]
[Thread 0x7ffefa7fc6c0 (LWP 603691) exited]
[New Thread 0x7ffefa7fc6c0 (LWP 603749)]
[New Thread 0x7fff7f7fc6c0 (LWP 603751)]
[New Thread 0x7ffefaffd6c0 (LWP 603864)]
[Thread 0x7ffefaffd6c0 (LWP 603864) exited]

** (epiphany:603226): CRITICAL **: 12:21:55.801: hspell_dict_check: assertion 'iso_word' failed

Thread 1 "epiphany" received signal SIGTRAP, Trace/breakpoint trap.
0x00007ffff7ad8fbd in g_logv () from /usr/lib/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff7ad8fbd in g_logv () at /usr/lib/libglib-2.0.so.0
#1  0x00007ffff7ad9224 in g_log () at /usr/lib/libglib-2.0.so.0
#2  0x00007fffd87bf1e3 in hspell_dict_check (me=me@entry=Python Exception <class 'ValueError'>: Variable 'static_fundamental_type_nodes' not found.
, word=word@entry=0x55555856d040 "׳לו", len=<optimized out>)
    at /usr/src/debug/enchant/enchant-2.8.0/providers/enchant_hspell.c:90
#3  0x00007fffedfb801a in enchant_dict_check (_self_=Python Exception <class 'ValueError'>: Variable 'static_fundamental_type_nodes' not found.
, word_buf=<optimized out>, len=<optimized out>)
    at /usr/src/debug/enchant/enchant-2.8.0/lib/dict.vala:137
#4  0x00007ffff59f743d in checkSpellingOfWord ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebCore/platform/text/enchant/TextCheckerEnchant.cpp:69
#5  0x00007ffff59f75c6 in checkSpellingOfString ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebCore/platform/text/enchant/TextCheckerEnchant.cpp:97
#6  0x00007ffff3b3e040 in checkSpellingOfString ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/UIProcess/gtk/TextCheckerGtk.cpp:145
#7  0x00007ffff3b3e59f in checkTextOfParagraph ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/UIProcess/gtk/TextCheckerGtk.cpp:266
#8  0x00007ffff39ba70a in checkTextOfParagraph ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/UIProcess/WebPageProxy.cpp:9276
#9  0x00007ffff35e5b38 in operator()<WTF::String, WTF::OptionSet<WebCore::TextCheckingType>, int> ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/HandleMessage.h:146
#10 __invoke_impl<void, (lambda at /home/yoseforb/pkg/webkitgtk-6.0/src/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/HandleMessage.h:145:9), WTF::String, WTF::OptionSet<WebCore::TextCheckingType>, int> ()
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/invoke.h:61
#11 __invoke<(lambda at /home/yoseforb/pkg/webkitgtk-6.0/src/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/HandleMessage.h:145:9), WTF::String, WTF::OptionSet<WebCore::TextCheckingType>, int> ()
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/invoke.h:96
#12 __apply_impl<(lambda at /home/yoseforb/pkg/webkitgtk-6.0/src/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/HandleMessage.h:145:9), std::tuple<WTF::String, WTF::OptionSet<WebCore::TextCheckingType>, int>, 0UL, 1UL, 2UL> ()
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/tuple:2921
#13 apply<(lambda at /home/yoseforb/pkg/webkitgtk-6.0/src/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/HandleMessage.h:145:9), std::tuple<WTF::String, WTF::OptionSet<WebCore::TextCheckingType>, int> > ()
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/tuple:2936
#14 callMemberFunction<WebKit::WebPageProxy, WebKit::WebPageProxy, void(WTF::String const&, WTF::OptionSet<WebCore::TextCheckingType>, int, WTF::CompletionHandler<void(WTF::Vector<WebCore::TextCheckingResult, 0ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&&)>&&), std::tuple<WTF::String, WTF::OptionSet<WebCore::TextCheckingType>, int>, void(WTF::Vector<WebCore::TextCheckingResult, 0ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&&)> () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/HandleMessage.h:144
--Type <RET> for more, q to quit, c to continue without paging--
#15 handleMessageSynchronous<Messages::WebPageProxy::CheckTextOfParagraph, WebKit::WebPageProxy, WebKit::WebPageProxy, void(WTF::String const&, WTF::OptionSet<WebCore::TextCheckingType>, int, WTF::CompletionHandler<void(WTF::Vector<WebCore::TextCheckingResult, 0ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&&)>&&)> () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/HandleMessage.h:275
#16 0x00007ffff35e3314 in didReceiveSyncMessage ()
    at /usr/src/debug/webkitgtk-6.0/build/DerivedSources/WebKit/WebPageProxyMessageReceiver.cpp:1111
#17 0x00007ffff3908c3c in dispatchSyncMessage ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/MessageReceiverMap.cpp:144
#18 0x00007ffff3a0740d in didReceiveSyncMessage ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/UIProcess/WebProcessProxy.cpp:1178
#19 0x00007ffff3902106 in dispatchSyncMessage ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/Connection.cpp:1217
#20 0x00007ffff390248a in dispatchMessage () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/Connection.cpp:1392
#21 0x00007ffff38fd292 in dispatch () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/Connection.cpp:148
#22 0x00007ffff38fd62d in dispatchMessagesAndResetDidScheduleDispatchMessagesForConnection ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/Connection.cpp:278
#23 0x00007ffff1b2eb1b in operator() () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WTF/wtf/Function.h:82
#24 performWork () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WTF/wtf/RunLoop.cpp:147
#25 0x00007ffff1b95d87 in operator() () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WTF/wtf/glib/RunLoopGLib.cpp:80
#26 __invoke () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WTF/wtf/glib/RunLoopGLib.cpp:79
#27 0x00007ffff1b94ecd in operator() () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WTF/wtf/glib/RunLoopGLib.cpp:53
#28 __invoke () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WTF/wtf/glib/RunLoopGLib.cpp:45
#29 0x00007ffff7acdd81 in ??? () at /usr/lib/libglib-2.0.so.0
#30 0x00007ffff7ad0047 in ??? () at /usr/lib/libglib-2.0.so.0
#31 0x00007ffff7ad07e2 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#32 0x00007ffff7d15f36 in g_application_run () at /usr/lib/libgio-2.0.so.0
#33 0x0000555555558772 in main (argc=<optimized out>, argv=<optimized out>) at ../epiphany/src/ephy-main.c:445
(gdb) bt full
#0  0x00007ffff7ad8fbd in g_logv () at /usr/lib/libglib-2.0.so.0
#1  0x00007ffff7ad9224 in g_log () at /usr/lib/libglib-2.0.so.0
#2  0x00007fffd87bf1e3 in hspell_dict_check (me=me@entry=Python Exception <class 'ValueError'>: Variable 'static_fundamental_type_nodes' not found.
, word=word@entry=0x55555856d040 "׳לו", len=<optimized out>)
    at /usr/src/debug/enchant/enchant-2.8.0/providers/enchant_hspell.c:90
        hspell_dict = 0x555555cf1c70
        iso_word = 0x0
        preflen = 0
        res = <optimized out>
        __func__ = "hspell_dict_check"
        _g_boolean_var_10 = <optimized out>
#3  0x00007fffedfb801a in enchant_dict_check (_self_=Python Exception <class 'ValueError'>: Variable 'static_fundamental_type_nodes' not found.
, word_buf=<optimized out>, len=<optimized out>)
    at /usr/src/debug/enchant/enchant-2.8.0/lib/dict.vala:137
        _tmp9_ = 0x7fffd87bf110 <hspell_dict_check>
        _tmp11_ = 0x55555856d040 "׳לו"
        _tmp13_ = <optimized out>
        _tmp10_ = 0x55555856d040 "׳לו"
        _tmp12_ = <optimized out>
        _tmp0_ = <optimized out>
        word = 0x55555856d040 "׳לו"
        _tmp1_ = 0x55555856d040 "׳לו"
        _tmp2_ = 0x55555856d040 "׳לו"
        _tmp3_ = <optimized out>
        _tmp4_ = <optimized out>
        _tmp5_ = 0x55555856d040 "׳לו"
        _tmp6_ = <optimized out>
        _tmp7_ = 0x55555856d040 "׳לו"
        _tmp8_ = 0x7fffd87bf110 <hspell_dict_check>
        result = <optimized out>
#4  0x00007ffff59f743d in checkSpellingOfWord ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebCore/platform/text/enchant/TextCheckerEnchant.cpp:69
#5  0x00007ffff59f75c6 in checkSpellingOfString ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebCore/platform/text/enchant/TextCheckerEnchant.cpp:97
#6  0x00007ffff3b3e040 in checkSpellingOfString ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/UIProcess/gtk/TextCheckerGtk.cpp:145
--Type <RET> for more, q to quit, c to continue without paging--
#7  0x00007ffff3b3e59f in checkTextOfParagraph ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/UIProcess/gtk/TextCheckerGtk.cpp:266
#8  0x00007ffff39ba70a in checkTextOfParagraph ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/UIProcess/WebPageProxy.cpp:9276
#9  0x00007ffff35e5b38 in operator()<WTF::String, WTF::OptionSet<WebCore::TextCheckingType>, int> ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/HandleMessage.h:146
#10 __invoke_impl<void, (lambda at /home/yoseforb/pkg/webkitgtk-6.0/src/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/HandleMessage.h:145:9), WTF::String, WTF::OptionSet<WebCore::TextCheckingType>, int> ()
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/invoke.h:61
#11 __invoke<(lambda at /home/yoseforb/pkg/webkitgtk-6.0/src/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/HandleMessage.h:145:9), WTF::String, WTF::OptionSet<WebCore::TextCheckingType>, int> ()
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/bits/invoke.h:96
#12 __apply_impl<(lambda at /home/yoseforb/pkg/webkitgtk-6.0/src/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/HandleMessage.h:145:9), std::tuple<WTF::String, WTF::OptionSet<WebCore::TextCheckingType>, int>, 0UL, 1UL, 2UL> ()
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/tuple:2921
#13 apply<(lambda at /home/yoseforb/pkg/webkitgtk-6.0/src/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/HandleMessage.h:145:9), std::tuple<WTF::String, WTF::OptionSet<WebCore::TextCheckingType>, int> > ()
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/14.1.1/../../../../include/c++/14.1.1/tuple:2936
#14 callMemberFunction<WebKit::WebPageProxy, WebKit::WebPageProxy, void(WTF::String const&, WTF::OptionSet<WebCore::TextCheckingType>, int, WTF::CompletionHandler<void(WTF::Vector<WebCore::TextCheckingResult, 0ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&&)>&&), std::tuple<WTF::String, WTF::OptionSet<WebCore::TextCheckingType>, int>, void(WTF::Vector<WebCore::TextCheckingResult, 0ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&&)> () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/HandleMessage.h:144
#15 handleMessageSynchronous<Messages::WebPageProxy::CheckTextOfParagraph, WebKit::WebPageProxy, WebKit::WebPageProxy, void(WTF::String const&, WTF::OptionSet<WebCore::TextCheckingType>, int, WTF::CompletionHandler<void(WTF::Vector<WebCore::TextCheckingResult, 0ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&&)>&&)> () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/HandleMessage.h:275
#16 0x00007ffff35e3314 in didReceiveSyncMessage ()
    at /usr/src/debug/webkitgtk-6.0/build/DerivedSources/WebKit/WebPageProxyMessageReceiver.cpp:1111
#17 0x00007ffff3908c3c in dispatchSyncMessage ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/MessageReceiverMap.cpp:144
#18 0x00007ffff3a0740d in didReceiveSyncMessage ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/UIProcess/WebProcessProxy.cpp:1178
#19 0x00007ffff3902106 in dispatchSyncMessage ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/Connection.cpp:1217
#20 0x00007ffff390248a in dispatchMessage () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/Connection.cpp:1392
--Type <RET> for more, q to quit, c to continue without paging--
#21 0x00007ffff38fd292 in dispatch () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/Connection.cpp:148
#22 0x00007ffff38fd62d in dispatchMessagesAndResetDidScheduleDispatchMessagesForConnection ()
    at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WebKit/Platform/IPC/Connection.cpp:278
#23 0x00007ffff1b2eb1b in operator() () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WTF/wtf/Function.h:82
#24 performWork () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WTF/wtf/RunLoop.cpp:147
#25 0x00007ffff1b95d87 in operator() () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WTF/wtf/glib/RunLoopGLib.cpp:80
#26 __invoke () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WTF/wtf/glib/RunLoopGLib.cpp:79
#27 0x00007ffff1b94ecd in operator() () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WTF/wtf/glib/RunLoopGLib.cpp:53
#28 __invoke () at /usr/src/debug/webkitgtk-6.0/webkitgtk-2.45.5/Source/WTF/wtf/glib/RunLoopGLib.cpp:45
#29 0x00007ffff7acdd81 in ??? () at /usr/lib/libglib-2.0.so.0
#30 0x00007ffff7ad0047 in ??? () at /usr/lib/libglib-2.0.so.0
#31 0x00007ffff7ad07e2 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#32 0x00007ffff7d15f36 in g_application_run () at /usr/lib/libgio-2.0.so.0
#33 0x0000555555558772 in main (argc=<optimized out>, argv=<optimized out>) at ../epiphany/src/ephy-main.c:445
        option_context = <optimized out>
        option_group = <optimized out>
        error = 0x0
        arbitrary_url = <optimized out>
        ctx = <optimized out>
        mode = EPHY_EMBED_SHELL_MODE_BROWSER
        status = <optimized out>
        flags = <optimized out>
        desktop_info = <optimized out>
        __func__ = "main"
(gdb)
```

### PR DESCRIPTION
**Pull request by yoseforb**
Epiphany's commit #70f8362e treats critical warnings as fatal, causing epiphany to crash when hspell_convert_to_iso8859_8 fails instead of just logging a warning.

The g_return_val_if_fail macro is intended to validate parameters passed to a function, meaning it should only be used to indicate programmer errors.

This commit adds g_return_val_if_fail to check only the function’s parameters, and replaces g_return_if_fail with g_warning for checking the result of hspell_convert_to_iso8859_8.

Fix #394

### CODE REVIEW

**Comment by yoseforb** [comment]
Sorry for the reopening, I didn't see how to update the old PR.

File: providers/enchant_hspell.c [hunk 1]
```diff
@@ -106,9 +114,18 @@ static char **
 hspell_dict_suggest (EnchantDict * me, const char *const word,
 		     size_t len, size_t * out_n_suggs)
 {
+	g_return_val_if_fail (me != NULL, NULL);
```
Comment (rrthomas) [inline providers/enchant_hspell.c]: These lines are unnecessary, as the caller has already checked them.

File: providers/enchant_hspell.c [hunk 2]
```diff
@@ -85,9 +85,17 @@ hspell_convert_to_iso8859_8 (EnchantDict *me, const char *const word, size_t len
 static int
 hspell_dict_check (EnchantDict * me, const char *const word, size_t len)
 {
+	g_return_val_if_fail (me != NULL, -1);
```
Comment (rrthomas) [inline providers/enchant_hspell.c]: These lines are unnecessary, as the caller has already checked these conditions.

**Comment by rrthomas** [comment]
Thanks for this; please just remove the extra calls to `g_return_val_if_fail`, as per comments.

**Comment by yoseforb** [comment]
> Thanks for this; please just remove the extra calls to `g_return_val_if_fail`, as per comments.

To remove all the calls to `g_return_val_if_fail`? I don't understand what calls is extra there.

**Comment by rrthomas** [comment]
I did mean all the calls. I just meant "extra" in the sense of "not previously present"!

File: providers/enchant_hspell.c [hunk 3]
```diff
@@ -86,8 +86,13 @@ static int
 hspell_dict_check (EnchantDict * me, const char *const word, size_t len)
 {
 	struct dict_radix *hspell_dict = (struct dict_radix *)me->user_data;
-	char *iso_word = hspell_convert_to_iso8859_8 (me, word, len);
-	g_return_val_if_fail (iso_word, -1);
+	char *iso_word = NULL;
+
+	iso_word = hspell_convert_to_iso8859_8 (me, word, len);
```
Comment (rrthomas) [inline providers/enchant_hspell.c]: Please could you just restore the original line 89, i.e. merge the declaration and assignment of `iso_word` in each case?

**Comment by rrthomas** [comment]
Thanks! This unlocks a minor simplification (and sorry for my slightly inept use of the review mechanism).

**Comment by rrthomas** [comment]
Many thanks for this, I'll make a point release soon.
